In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [ ]:
#You can download both files from https://mega.nz/folder/CrI2GASD#Zej_fEzRDnYHflmgXQQCvA
firstFilePath = 'lcf_annual.csv'
secondFilePath = 'lcf_proxy.csv'

In [3]:
annualLCFDataFrame = pd.read_csv(firstFilePath, sep=',',index_col=False,header=0,encoding='Latin-1',engine='python' )
proxyLCFDataFrame = pd.read_csv(secondFilePath, sep=',',index_col=False,header=0,encoding='Latin-1',engine='python' )

monthDictionary = {
                    1:'January',
                    2:'February',
                    3:'March',
                    4:'April',
                    5:'May',
                    6:'June',
                    7:'July',
                    8:'August',
                    9:'September',
                    10:'October',
                    11:'November',
                    12:'Dicember'
                    }

In [ ]:
#c) Aplica al menos 5 técnicas de exploración de datos y confirma que tus datos están cargados correctamente.

URL                           str
acceptanceDatetime        float64
accessionNumber               str
type                          str
publicDocumentCount         int64
period                    float64
filingDate                  int64
dateOfFilingDateChange    float64
effectivenessDate         float64
sros                          str
name                          str
cik                       float64
sic                       float64
IRSNumber                     str
stateOfIncorporation          str
fiscalYearend             float64
formType                      str
act                           str
fileNumber                    str
filmNumber                float64
businessStreet1               str
businessStreet2               str
businessCity                  str
businessState                 str
businessZip                   str
businessPhone                 str
mailingStreet1                str
mailingStreet2                str
mailingCity                   str
mailingState                  str
mailingZip                    str
formerName                    str
dateChanged                   str
dtype: object

In [4]:
annualLCFDataFrame.columns

Index(['URL', 'acceptanceDatetime', 'accessionNumber', 'type',
       'publicDocumentCount', 'period', 'filingDate', 'dateOfFilingDateChange',
       'sros', 'name', 'cik', 'sic', 'IRSNumber', 'stateOfIncorporation',
       'fiscalYearend', 'formType', 'act', 'fileNumber', 'filmNumber',
       'businessStreet1', 'businessStreet2', 'businessCity', 'businessState',
       'businessZip', 'businessPhone', 'mailingStreet1', 'mailingStreet2',
       'mailingCity', 'mailingState', 'mailingZip', 'formerName',
       'dateChanged'],
      dtype='str')

In [5]:
annualLCFDataFrame.head()

,URL,acceptanceDatetime,accessionNumber,type,publicDocumentCount,period,filingDate,dateOfFilingDateChange,sros,name,...,businessState,businessZip,businessPhone,mailingStreet1,mailingStreet2,mailingCity,mailingState,mailingZip,formerName,dateChanged
0,https://www.sec.gov/Archives/edgar/data/29082/...,NaN,0000950131-94-000021,10-K,2,19930930.0,19931222,19940119.0,NaN,DISNEY WALT CO,...,CA,91521,8185601000,NaN,NaN,NaN,NaN,NaN,DISNEY WALT PRODUCTIONS,19860221
1,https://www.sec.gov/Archives/edgar/data/353944...,NaN,0000353944-94-000005,10-K,9,19930930.0,19931223,19931222.0,NONE,INTERNATIONAL GAME TECHNOLOGY,...,NV,89502,7026880100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.sec.gov/Archives/edgar/data/32377/...,NaN,0000032377-94-000001,10-K,2,19930930.0,19931213,19940210.0,NaN,ELIZABETHTOWN GAS CO,...,NJ,07083,9082895000,ONE ELIZABETHTOWN PLAZA,NaN,UNION,NJ,07083,ELIZABETHTOWN CONSOLIDATED GAS CO,19700828
3,https://www.sec.gov/Archives/edgar/data/17206/...,NaN,0000017206-94-000007,10-K/A,1,19921231.0,19931222,19940119.0,NaN,CAPITAL HOLDING CORP,...,KY,40202,5025602000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.sec.gov/Archives/edgar/data/60512/...,NaN,0000060512-94-000006,10-K/A,1,19921231.0,19931007,19940111.0,NaN,LOUISIANA LAND & EXPLORATION CO,...,LA,70112,5045666500,NaN,P O BOX 60350,NEW ORLEANS,LA,70160,NaN,NaN

In [6]:
annualLCFDataFrame.tail()

,URL,acceptanceDatetime,accessionNumber,type,publicDocumentCount,period,filingDate,dateOfFilingDateChange,sros,name,...,businessState,businessZip,businessPhone,mailingStreet1,mailingStreet2,mailingCity,mailingState,mailingZip,formerName,dateChanged
264699,https://www.sec.gov/Archives/edgar/data/924396...,2.023110e+13,0001493152-23-039011,10-K,75,20230731.0,20231101,20231101.0,NaN,"OpenLocker Holdings, Inc.",...,FL,33401,305-351-9195,1700 PALM BEACH LAKES BLVD,SUITE 820,WEST PALM BEACH,FL,33401,"Descrypto Holdings, Inc.|W Technologies, Inc.|...",20220203|20071130|20061030
264700,https://www.sec.gov/Archives/edgar/data/170175...,2.023110e+13,0001628280-23-036432,10-K/A,72,20230129.0,20231102,20231102.0,NaN,Lovesac Co,...,CT,06901,203-817-2279,"TWO LANDMARK SQUARE, SUITE 300",NaN,STAMFORD,CT,06901,NaN,NaN
264701,https://www.sec.gov/Archives/edgar/data/316253...,2.023110e+13,0001213900-23-083566,10-K,110,20230731.0,20231103,20231103.0,NaN,ENZO BIOCHEM INC,...,NY,11735,5167555500,ENZO BIOCHEM INC,60 EXECUTIVE BLVD,FARMINGDALE,NY,11735,NaN,NaN
264702,https://www.sec.gov/Archives/edgar/data/320193...,2.023110e+13,0000320193-23-000106,10-K,96,20230930.0,20231103,20231102.0,NaN,Apple Inc.,...,CA,95014,(408) 996-1010,ONE APPLE PARK WAY,NaN,CUPERTINO,CA,95014,APPLE INC|APPLE COMPUTER INC,20070109|19970808
264703,https://www.sec.gov/Archives/edgar/data/857949...,2.023110e+13,0001213900-23-083514,10-K,101,20230630.0,20231103,20231103.0,NaN,"China Green Agriculture, Inc.",...,F4,710065,3034996000,"3RD FLOOR, BOROUGH A, BLOCK A. NO.181,","SOUTH TAIBAI ROAD,","XIAN, SHAANXI PROVINCE,",F4,710065,DISCOVERY TECHNOLOGIES INC|DISCOVERY TECHNOLOG...,20071114|19920703|19900613

In [36]:
annualLCFDataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 264704 entries, 0 to 264703
Data columns (total 32 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   URL                     264704 non-null  str
 1   acceptanceDatetime      205216 non-null  float64
 2   accessionNumber         264704 non-null  str
 3   type                    264704 non-null  str
 4   publicDocumentCount     264704 non-null  int64
 5   period                  264701 non-null  float64
 6   filingDate              264704 non-null  int64
 7   dateOfFilingDateChange  182775 non-null  float64
 8   sros                    26515 non-null   str
 9   name                    264704 non-null  str
 10  cik                     264704 non-null  int64
 11  sic                     259973 non-null  float64
 12  IRSNumber               249747 non-null  str
 13  stateOfIncorporation    242548 non-null  str
 14  fiscalYearend           254434 non-null  float64
 15  formType                264704 non-null  str
 16  act                     264704 non-null  str
 17  fileNumber              264704 non-null  str
 18  filmNumber              264636 non-null  float64
 19  businessStreet1         263140 non-null  str
 20  businessStreet2         107150 non-null  str
 21  businessCity            263084 non-null  str
 22  businessState           262898 non-null  str
 23  businessZip             262363 non-null  str
 24  businessPhone           257653 non-null  str
 25  mailingStreet1          243316 non-null  str
 26  mailingStreet2          103273 non-null  str
 27  mailingCity             244809 non-null  str
 28  mailingState            244549 non-null  str
 29  mailingZip              244189 non-null  str
 30  formerName              107138 non-null  str
 31  dateChanged             107138 non-null  str
dtypes: float64(6), int64(3), str(23)
memory usage: 64.6 MB

In [7]:
annualLCFDataFrame.dtypes

URL                           str
acceptanceDatetime        float64
accessionNumber               str
type                          str
publicDocumentCount         int64
period                    float64
filingDate                  int64
dateOfFilingDateChange    float64
sros                          str
name                          str
cik                         int64
sic                       float64
IRSNumber                     str
stateOfIncorporation          str
fiscalYearend             float64
formType                      str
act                           str
fileNumber                    str
filmNumber                float64
businessStreet1               str
businessStreet2               str
businessCity                  str
businessState                 str
businessZip                   str
businessPhone                 str
mailingStreet1                str
mailingStreet2                str
mailingCity                   str
mailingState                  str
mailingZip                    str
formerName                    str
dateChanged                   str
dtype: object

In [37]:
proxyLCFDataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 341397 entries, 0 to 341396
Data columns (total 33 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   URL                     341397 non-null  str
 1   acceptanceDatetime      266532 non-null  float64
 2   accessionNumber         341397 non-null  str
 3   type                    341397 non-null  str
 4   publicDocumentCount     341397 non-null  int64
 5   period                  203388 non-null  float64
 6   filingDate              341397 non-null  int64
 7   dateOfFilingDateChange  243077 non-null  float64
 8   effectivenessDate       221471 non-null  float64
 9   sros                    32969 non-null   str
 10  name                    341380 non-null  str
 11  cik                     341380 non-null  float64
 12  sic                     279897 non-null  float64
 13  IRSNumber               335586 non-null  str
 14  stateOfIncorporation    311898 non-null  str
 15  fiscalYearend           329339 non-null  float64
 16  formType                341380 non-null  str
 17  act                     341380 non-null  str
 18  fileNumber              341379 non-null  str
 19  filmNumber              341324 non-null  float64
 20  businessStreet1         339981 non-null  str
 21  businessStreet2         136159 non-null  str
 22  businessCity            339935 non-null  str
 23  businessState           339691 non-null  str
 24  businessZip             339000 non-null  str
 25  businessPhone           337183 non-null  str
 26  mailingStreet1          316555 non-null  str
 27  mailingStreet2          134701 non-null  str
 28  mailingCity             318470 non-null  str
 29  mailingState            318103 non-null  str
 30  mailingZip              317735 non-null  str
 31  formerName              164460 non-null  str
 32  dateChanged             164460 non-null  str
dtypes: float64(8), int64(2), str(23)
memory usage: 86.0 MB

In [ ]:
proxyLCFDataFrame.columns

In [ ]:
proxyLCFDataFrame.head()

In [ ]:
proxyLCFDataFrame.tail()

In [ ]:
proxyLCFDataFrame.info()

In [ ]:
proxyLCFDataFrame.dtypes

In [ ]:
#b) Valida el tipo de dato que contiene las columnas y realiza los métodos de reemplazar o limpiar caracteres especialestales como “espacios”, “símbolo moneda”, etc. 
#c) Revisa que la columna de fecha tenga el formato correspondiente y utiliza la función de conversión al formato ‘%Y-%m-%d %H:%M:%S'.

In [8]:
annualLCFDataFrame['filingDate']

0         19931222
1         19931223
2         19931213
3         19931222
4         19931007
            ...
264699    20231101
264700    20231102
264701    20231103
264702    20231103
264703    20231103
Name: filingDate, Length: 264704, dtype: int64

In [9]:
annualLCFDataFrame['filingDate'] = pd.to_datetime(annualLCFDataFrame['filingDate'], format='ISO8601' )

In [28]:
annualLCFDataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 264704 entries, 0 to 264703
Data columns (total 32 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   URL                     264704 non-null  str
 1   acceptanceDatetime      264704 non-null  datetime64[ns]
 2   accessionNumber         264704 non-null  str
 3   type                    264704 non-null  str
 4   publicDocumentCount     264704 non-null  int64
 5   period                  264701 non-null  float64
 6   filingDate              264704 non-null  datetime64[us]
 7   dateOfFilingDateChange  182775 non-null  float64
 8   sros                    26515 non-null   str
 9   name                    264704 non-null  str
 10  cik                     264704 non-null  int64
 11  sic                     259973 non-null  float64
 12  IRSNumber               249747 non-null  str
 13  stateOfIncorporation    242548 non-null  str
 14  fiscalYearend           254434 non-null  float64
 15  formType                264704 non-null  str
 16  act                     264704 non-null  str
 17  fileNumber              264704 non-null  str
 18  filmNumber              264636 non-null  float64
 19  businessStreet1         263140 non-null  str
 20  businessStreet2         107150 non-null  str
 21  businessCity            263084 non-null  str
 22  businessState           262898 non-null  str
 23  businessZip             262363 non-null  str
 24  businessPhone           257653 non-null  str
 25  mailingStreet1          243316 non-null  str
 26  mailingStreet2          103273 non-null  str
 27  mailingCity             244809 non-null  str
 28  mailingState            244549 non-null  str
 29  mailingZip              244189 non-null  str
 30  formerName              107138 non-null  str
 31  dateChanged             107138 non-null  str
dtypes: datetime64[ns](1), datetime64[us](1), float64(5), int64(2), str(23)
memory usage: 64.6 MB

In [11]:
annualLCFDataFrame['acceptanceDatetime'] = annualLCFDataFrame['acceptanceDatetime'].astype(str)

In [14]:
annualLCFDataFrame['acceptanceDatetime'] = annualLCFDataFrame['acceptanceDatetime'].str.slice(start=0,stop=8 )

In [27]:
annualLCFDataFrame['acceptanceDatetime']

0        1970-01-01
1        1970-01-01
2        1970-01-01
3        1970-01-01
4        1970-01-01
            ...
264699   2023-11-01
264700   2023-11-02
264701   2023-11-03
264702   2023-11-02
264703   2023-11-03
Name: acceptanceDatetime, Length: 264704, dtype: datetime64[ns]

In [26]:
annualLCFDataFrame['acceptanceDatetime'] = pd.to_datetime(annualLCFDataFrame['acceptanceDatetime'],format='mixed')

In [17]:

annualLCFDataFrame['acceptanceDatetime'] = annualLCFDataFrame['acceptanceDatetime'].fillna(0)

In [ ]:
#annualLCFDataFrame['dateChanged']
#aqui quise convertir la ultima columna, pero como no habia consistencia, no acepto expandir a 4 columnas

In [39]:
annualLCFDataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 264704 entries, 0 to 264703
Data columns (total 36 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   URL                     264704 non-null  str
 1   acceptanceDatetime      264704 non-null  datetime64[ns]
 2   accessionNumber         264704 non-null  str
 3   type                    264704 non-null  str
 4   publicDocumentCount     264704 non-null  int64
 5   period                  264701 non-null  float64
 6   filingDate              264704 non-null  datetime64[us]
 7   dateOfFilingDateChange  182775 non-null  float64
 8   sros                    26515 non-null   str
 9   name                    264704 non-null  str
 10  cik                     264704 non-null  int64
 11  sic                     259973 non-null  float64
 12  IRSNumber               249747 non-null  str
 13  stateOfIncorporation    242548 non-null  str
 14  fiscalYearend           254434 non-null  float64
 15  formType                264704 non-null  str
 16  act                     264704 non-null  str
 17  fileNumber              264704 non-null  str
 18  filmNumber              264636 non-null  float64
 19  businessStreet1         263140 non-null  str
 20  businessStreet2         107150 non-null  str
 21  businessCity            263084 non-null  str
 22  businessState           262898 non-null  str
 23  businessZip             262363 non-null  str
 24  businessPhone           257653 non-null  str
 25  mailingStreet1          243316 non-null  str
 26  mailingStreet2          103273 non-null  str
 27  mailingCity             244809 non-null  str
 28  mailingState            244549 non-null  str
 29  mailingZip              244189 non-null  str
 30  formerName              107138 non-null  str
 31  dateChanged             107138 non-null  str
 32  Date-Change1            107138 non-null  str
 33  Date-Change2            37878 non-null   str
 34  Date-Change3            13924 non-null   str
 35  Date-Change4            11 non-null      str
dtypes: datetime64[ns](1), datetime64[us](1), float64(5), int64(2), str(27)
memory usage: 72.7 MB

In [35]:
annualLCFDataFrame['dateChanged']

0                           19860221
1                                NaN
2                           19700828
3                                NaN
4                                NaN
                     ...
264699    20220203|20071130|20061030
264700                           NaN
264701                           NaN
264702             20070109|19970808
264703    20071114|19920703|19900613
Name: dateChanged, Length: 264704, dtype: str

In [38]:
annualLCFDataFrame[['Date-Change1','Date-Change2','Date-Change3','Date-Change4']] = annualLCFDataFrame['dateChanged'].str.split('|',expand=True )

In [32]:
annualLCFDataFrame['dateChanged'].str.split('|',expand=True )

               0         1         2    3
0       19860221       NaN       NaN  NaN
1            NaN       NaN       NaN  NaN
2       19700828       NaN       NaN  NaN
3            NaN       NaN       NaN  NaN
4            NaN       NaN       NaN  NaN
...          ...       ...       ...  ...
264699  20220203  20071130  20061030  NaN
264700       NaN       NaN       NaN  NaN
264701       NaN       NaN       NaN  NaN
264702  20070109  19970808       NaN  NaN
264703  20071114  19920703  19900613  NaN

[264704 rows x 4 columns]

In [43]:
#annualLCFDataFrame['dateChanged'] = pd.to_datetime(annualLCFDataFrame['dateChanged'], format='ISO8601')
annualLCFDataFrame['Date-Change1'] = pd.to_datetime(annualLCFDataFrame['Date-Change1'], format='ISO8601')
annualLCFDataFrame['Date-Change2'] = pd.to_datetime(annualLCFDataFrame['Date-Change2'], format='ISO8601')
annualLCFDataFrame['Date-Change3'] = pd.to_datetime(annualLCFDataFrame['Date-Change3'], format='ISO8601')
annualLCFDataFrame['Date-Change4'] = pd.to_datetime(annualLCFDataFrame['Date-Change4'], format='ISO8601')

In [44]:
annualLCFDataFrame['period'] = pd.to_datetime(annualLCFDataFrame['period'],format='ISO8601')

In [45]:
annualLCFDataFrame['sros'] = annualLCFDataFrame['sros'].astype(str)
annualLCFDataFrame['sros'] = annualLCFDataFrame['sros'].fillna(0)

In [ ]:
annualLCFDataFrame['mailingStreet1'] = annualLCFDataFrame['mailingStreet1'].fillna(0)
annualLCFDataFrame['mailingStreet2'] = annualLCFDataFrame['mailingStreet2'].fillna(0)
annualLCFDataFrame['mailingState'] = annualLCFDataFrame['mailingState'].fillna(0)
annualLCFDataFrame['mailingZip'] = annualLCFDataFrame['mailingZip'].fillna(0)
annualLCFDataFrame['formerName'] = annualLCFDataFrame['formerName'].fillna(0)

In [48]:
proxyLCFDataFrame['filingDate'] = pd.to_datetime(proxyLCFDataFrame['filingDate'],format='ISO8601' )

In [49]:
proxyLCFDataFrame['acceptanceDatetime'] = proxyLCFDataFrame['acceptanceDatetime'].astype(str)

In [50]:
proxyLCFDataFrame['acceptanceDatetime'] = proxyLCFDataFrame['acceptanceDatetime'].str.slice(start=0,stop=8)

In [51]:
proxyLCFDataFrame['acceptanceDatetime'] = pd.to_datetime(proxyLCFDataFrame['acceptanceDatetime'],format='ISO8601')

In [52]:
proxyLCFDataFrame['acceptanceDatetime'] = proxyLCFDataFrame['acceptanceDatetime'].fillna(0)

In [53]:
proxyLCFDataFrame['dateOfFilingDateChange'] = pd.to_datetime(proxyLCFDataFrame['dateOfFilingDateChange'],format='ISO8601')

In [54]:
proxyLCFDataFrame['dateOfFilingDateChange'] = proxyLCFDataFrame['dateOfFilingDateChange'].fillna(0)

In [55]:
proxyLCFDataFrame['period'] = pd.to_datetime(proxyLCFDataFrame['period'],format='ISO8601')

In [56]:
proxyLCFDataFrame['period'] = proxyLCFDataFrame['period'].fillna(0)

In [57]:
proxyLCFDataFrame['mailingStreet1'] = proxyLCFDataFrame['mailingStreet1'].fillna(0)
proxyLCFDataFrame['mailingStreet2'] = proxyLCFDataFrame['mailingStreet2'].fillna(0)
proxyLCFDataFrame['mailingCity'] = proxyLCFDataFrame['mailingCity'].fillna(0)
proxyLCFDataFrame['mailingState'] = proxyLCFDataFrame['mailingState'].fillna(0)
proxyLCFDataFrame['mailingZip'] = proxyLCFDataFrame['mailingZip'].fillna(0)
proxyLCFDataFrame['formerName'] = proxyLCFDataFrame['formerName'].fillna(0)

In [ ]:
#d) Extraiga de su columna de Fechas, la información referente al Año, Mesy Nombre de Mes.
#me enfoco en filing year porque si no me equivoco esta es la fecha importante o due para presentarse ante el IRS

In [58]:

annualLCFDataFrame['filingDateYear'] = annualLCFDataFrame['filingDate'].dt.year
annualLCFDataFrame['filingDateMonth'] = annualLCFDataFrame['filingDate'].dt.month
annualLCFDataFrame['filingDateMonth'] = annualLCFDataFrame['filingDateMonth'].replace(monthDictionary)

proxyLCFDataFrame['filingDateYear'] = proxyLCFDataFrame['filingDate'].dt.year
proxyLCFDataFrame['filingDateMonth'] = proxyLCFDataFrame['filingDate'].dt.month
proxyLCFDataFrame['filingDateMonth'] = proxyLCFDataFrame['filingDateMonth'].replace(monthDictionary)

In [61]:
concatIRSFilingDataFrame

,URL,acceptanceDatetime,accessionNumber,type,publicDocumentCount,period,filingDate,dateOfFilingDateChange,sros,name,...,mailingZip,formerName,dateChanged,Date-Change1,Date-Change2,Date-Change3,Date-Change4,filingDateYear,filingDateMonth,effectivenessDate
0,https://www.sec.gov/Archives/edgar/data/29082/...,1970-01-01 00:00:00,0000950131-94-000021,10-K,2,1993-09-30 00:00:00,1993-12-22,19940119.0,0,DISNEY WALT CO,...,0,DISNEY WALT PRODUCTIONS,19860221,1986-02-21,NaT,NaT,NaT,1993,Dicember,NaN
1,https://www.sec.gov/Archives/edgar/data/353944...,1970-01-01 00:00:00,0000353944-94-000005,10-K,9,1993-09-30 00:00:00,1993-12-23,19931222.0,NONE,INTERNATIONAL GAME TECHNOLOGY,...,0,0,NaN,NaT,NaT,NaT,NaT,1993,Dicember,NaN
2,https://www.sec.gov/Archives/edgar/data/32377/...,1970-01-01 00:00:00,0000032377-94-000001,10-K,2,1993-09-30 00:00:00,1993-12-13,19940210.0,0,ELIZABETHTOWN GAS CO,...,07083,ELIZABETHTOWN CONSOLIDATED GAS CO,19700828,1970-08-28,NaT,NaT,NaT,1993,Dicember,NaN
3,https://www.sec.gov/Archives/edgar/data/17206/...,1970-01-01 00:00:00,0000017206-94-000007,10-K/A,1,1992-12-31 00:00:00,1993-12-22,19940119.0,0,CAPITAL HOLDING CORP,...,0,0,NaN,NaT,NaT,NaT,NaT,1993,Dicember,NaN
4,https://www.sec.gov/Archives/edgar/data/60512/...,1970-01-01 00:00:00,0000060512-94-000006,10-K/A,1,1992-12-31 00:00:00,1993-10-07,19940111.0,0,LOUISIANA LAND & EXPLORATION CO,...,70160,0,NaN,NaT,NaT,NaT,NaT,1993,October,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606096,https://www.sec.gov/Archives/edgar/data/88053/...,2023-11-03 00:00:00,0000088053-23-000731,DEF 14C,1,2023-11-03 00:00:00,2023-11-03,2023-11-03 00:00:00,NaN,"DEUTSCHE DWS INTERNATIONAL FUND, INC.",...,10022-6225,"DEUTSCHE INTERNATIONAL FUND, INC.|DWS INTERNAT...",20140811|20060207|19920703,NaT,NaT,NaT,NaT,2023,November,NaN
606097,https://www.sec.gov/Archives/edgar/data/863900...,2023-11-03 00:00:00,0001839882-23-029733,DEFA14A,3,0,2023-11-03,2023-11-03 00:00:00,NaN,MEXICO EQUITY & INCOME FUND INC,...,53202,MEXICO CONVERTIBLE ADVANTAGE FUND INC|MEXICO A...,19900807|19900805,NaT,NaT,NaT,NaT,2023,November,NaN
606098,https://www.sec.gov/Archives/edgar/data/924805...,2023-11-03 00:00:00,0000924805-23-000106,DEFA14A,1,0,2023-11-03,2023-11-03 00:00:00,NaN,Freedom Holding Corp.,...,10178-0060,BMB MUNAI INC|INTERUNION FINANCIAL CORP,20031218|19960719,NaT,NaT,NaT,NaT,2023,November,NaN
606099,https://www.sec.gov/Archives/edgar/data/98338/...,2023-11-03 00:00:00,0001213900-23-083562,DEF 14A,5,2023-12-07 00:00:00,2023-11-03,2023-11-03 00:00:00,NaN,TSR INC,...,11788,TIME SHARING RESOURCES INC,19840129,NaT,NaT,NaT,NaT,2023,November,NaN
606100,https://www.sec.gov/Archives/edgar/data/886244...,2023-11-03 00:00:00,0001104659-23-114350,DEFA14A,5,0,2023-11-03,2023-11-03 00:00:00,NaN,UBS FUNDS,...,60606,BRINSON FUNDS INC,19920929,NaT,NaT,NaT,NaT,2023,November,NaN

In [63]:
concatIRSFilingDataFrame = pd.concat([annualLCFDataFrame,proxyLCFDataFrame],ignore_index=True,axis=0 )

In [64]:
concatIRSFilingDataFrame

,URL,acceptanceDatetime,accessionNumber,type,publicDocumentCount,period,filingDate,dateOfFilingDateChange,sros,name,...,mailingZip,formerName,dateChanged,Date-Change1,Date-Change2,Date-Change3,Date-Change4,filingDateYear,filingDateMonth,effectivenessDate
0,https://www.sec.gov/Archives/edgar/data/29082/...,1970-01-01 00:00:00,0000950131-94-000021,10-K,2,1993-09-30 00:00:00,1993-12-22,19940119.0,0,DISNEY WALT CO,...,0,DISNEY WALT PRODUCTIONS,19860221,1986-02-21,NaT,NaT,NaT,1993,Dicember,NaN
1,https://www.sec.gov/Archives/edgar/data/353944...,1970-01-01 00:00:00,0000353944-94-000005,10-K,9,1993-09-30 00:00:00,1993-12-23,19931222.0,NONE,INTERNATIONAL GAME TECHNOLOGY,...,0,0,NaN,NaT,NaT,NaT,NaT,1993,Dicember,NaN
2,https://www.sec.gov/Archives/edgar/data/32377/...,1970-01-01 00:00:00,0000032377-94-000001,10-K,2,1993-09-30 00:00:00,1993-12-13,19940210.0,0,ELIZABETHTOWN GAS CO,...,07083,ELIZABETHTOWN CONSOLIDATED GAS CO,19700828,1970-08-28,NaT,NaT,NaT,1993,Dicember,NaN
3,https://www.sec.gov/Archives/edgar/data/17206/...,1970-01-01 00:00:00,0000017206-94-000007,10-K/A,1,1992-12-31 00:00:00,1993-12-22,19940119.0,0,CAPITAL HOLDING CORP,...,0,0,NaN,NaT,NaT,NaT,NaT,1993,Dicember,NaN
4,https://www.sec.gov/Archives/edgar/data/60512/...,1970-01-01 00:00:00,0000060512-94-000006,10-K/A,1,1992-12-31 00:00:00,1993-10-07,19940111.0,0,LOUISIANA LAND & EXPLORATION CO,...,70160,0,NaN,NaT,NaT,NaT,NaT,1993,October,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606096,https://www.sec.gov/Archives/edgar/data/88053/...,2023-11-03 00:00:00,0000088053-23-000731,DEF 14C,1,2023-11-03 00:00:00,2023-11-03,2023-11-03 00:00:00,NaN,"DEUTSCHE DWS INTERNATIONAL FUND, INC.",...,10022-6225,"DEUTSCHE INTERNATIONAL FUND, INC.|DWS INTERNAT...",20140811|20060207|19920703,NaT,NaT,NaT,NaT,2023,November,NaN
606097,https://www.sec.gov/Archives/edgar/data/863900...,2023-11-03 00:00:00,0001839882-23-029733,DEFA14A,3,0,2023-11-03,2023-11-03 00:00:00,NaN,MEXICO EQUITY & INCOME FUND INC,...,53202,MEXICO CONVERTIBLE ADVANTAGE FUND INC|MEXICO A...,19900807|19900805,NaT,NaT,NaT,NaT,2023,November,NaN
606098,https://www.sec.gov/Archives/edgar/data/924805...,2023-11-03 00:00:00,0000924805-23-000106,DEFA14A,1,0,2023-11-03,2023-11-03 00:00:00,NaN,Freedom Holding Corp.,...,10178-0060,BMB MUNAI INC|INTERUNION FINANCIAL CORP,20031218|19960719,NaT,NaT,NaT,NaT,2023,November,NaN
606099,https://www.sec.gov/Archives/edgar/data/98338/...,2023-11-03 00:00:00,0001213900-23-083562,DEF 14A,5,2023-12-07 00:00:00,2023-11-03,2023-11-03 00:00:00,NaN,TSR INC,...,11788,TIME SHARING RESOURCES INC,19840129,NaT,NaT,NaT,NaT,2023,November,NaN
606100,https://www.sec.gov/Archives/edgar/data/886244...,2023-11-03 00:00:00,0001104659-23-114350,DEFA14A,5,0,2023-11-03,2023-11-03 00:00:00,NaN,UBS FUNDS,...,60606,BRINSON FUNDS INC,19920929,NaT,NaT,NaT,NaT,2023,November,NaN

In [62]:
#annualLCFDataFrame['accessionNumber'] == proxyLCFDataFrame['accessionNumber']

ValueError: Can only compare identically-labeled Series objects

In [65]:
leftFilingDataFrame = pd.merge(annualLCFDataFrame, proxyLCFDataFrame,
                            left_on='accessionNumber',
                            right_on='accessionNumber',
                            how='left'
                    )